language: cpp
sudo: true
addons:
  before_install:
    - apt-get install software-properties-common
    - add-apt-repository ppa:george-edison55/cmake-3.x
    - apt-get update
    - apt-get install cmake
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - g++-4.8
      - gcc-4.8
      - libglu1-mesa-dev
      - libxxf86vm-dev 
      - cmake
matrix:
  include:
    - os: linux
      compiler: gcc-4.8
      script:
        - cmake -DCMAKE_CXX_COMPILER=g++-4.8 -DCMAKE_CC_COMPILER=gcc-4.8
        - make -j 2
    - os: osx
      compiler: clang
      script:
        - make -j 2